language: python

jobs:
  include:
    # perform a linux build
    - services: docker

env:
  global:
    - TWINE_USERNAME=__token__
    - CIBW_SKIP="cp2* pp2*"

cache:
    - directories:
        - /home/travis/build/ANTsX/itkbuild
        - /home/travis/build/ANTsX/itksource
        - /home/travis/build/ANTsX/ANTsPy/ants/lib
        - /home/travis/build/ANTsX/ANTsPy/build
        - /usr/local

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      CMAKE_INSTALLER=install-cmake.sh && \
        curl -sSL https://cmake.org/files/v3.11/cmake-3.11.3-Linux-x86_64.sh -o ${CMAKE_INSTALLER} && \
        chmod +x ${CMAKE_INSTALLER} && \
        sudo ./${CMAKE_INSTALLER} --prefix=/usr/local --skip-license
    fi
  - alias cmake=/usr/local/bin/cmake
  - export PATH=/usr/local/bin/cmake/bin:/usr/local/bin:${PATH}
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      echo "need cmake 3.12" && \
        brew update && \
        brew install ccache && \
        brew upgrade cmake && \
        export PATH="/usr/local/opt/ccache/libexec:$PATH"
    fi
  - pip3 install scipy==1.2 pandas numpy matplotlib sklearn statsmodels nibabel
  - pip3 install coveralls plotly webcolors scikit-image;
  - cd ..
  - if [ ! -f /home/travis/build/ANTsX/itkbuild/ITKConfig.cmake ]; then bash ${TRAVIS_BUILD_DIR}/scripts/configure_ITK.sh; fi
  - temp=`find ./ -name "ITKConfig.cmake"`
  - echo $temp
  - cd ${TRAVIS_BUILD_DIR}
  - export ITK_DIR=/home/travis/build/ANTsX/itkbuild/

install:
  - python3 -m pip install cibuildwheel==1.3.0
  - python3 setup.py install
#  - travis_wait 30 python3 setup.py sdist bdist_wheel

script:
  # build the wheels, put them into './wheelhouse'
  - ./tests/run_tests_travis.sh
#  - python3 -m cibuildwheel --output-dir wheelhouse
#  - python3 -m pip install twine
#  - ls wheelhouse/*whl

# FIXME see https://github.com/joerick/cibuildwheel

after_success:
  # if the release was tagged, upload them to PyPI
  - |
    if [[ $TRAVIS_TAG ]]; then
      echo nada # python3 -m twine upload wheelhouse/*.whl
    fi
